CREATE TABLE companies (
  id UUID PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  nit VARCHAR(255) NOT NULL,
  area VARCHAR(255) NOT NULL
);
