development:
  dialect: postgres 
  url: {{ envOr "DATABASE_URL" "postgres://postgres:123@127.0.0.1:5432/project_storm_development?sslmode=disable" }}

test:
  dialect: postgres
  url: {{ envOr "DATABASE_URL" "postgres://postgres:123@127.0.0.1:5432/project_storm_production?sslmode=disable" }}

production:
  pool: 20
  dialect: postgres
  url: {{ envOr "DATABASE_URL" "postgres://postgres:123@127.0.0.1:5432/project_storm_test?sslmode=disable" }}