development:
  dialect: postgres 
  url: {{ envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/Project_Storm_development?sslmode=disable" }}

test:
  dialect: postgres
  url: {{ envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/Project_Storm_test?sslmode=disable" }}

production:
  pool: 20
  dialect: postgres
  url: {{ envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/Project_Storm_production?sslmode=disable" }}